---

- name: Include vars
  include_vars:
    depth: 2
    dir: "{{ ansible_env.HOME }}/.config"
    files_matching: "^git_repos.*\\.yaml$"
    name: git_repos
  ignore_errors: yes

- include: repo_dir.yml
  vars:
    repo_dir: "{{ item.key }}"
    config: "{{ item.value }}"
  loop: "{{ git_repos|default({})|dict2items }}"

