---

- name: "Ensure {{ repo_dir }} exists"
  file:
    path: "{{ ansible_env.HOME }}/src/{{ repo_dir }}"
    state: directory

- debug: var=repos

- name: "Clone repo {{ repo.name }} to {{ repo_dir }}"
  git:
    accept_hostkey: true
    dest: "{{ ansible_env.HOME }}/src/{{ repo_dir }}/{{ repo.name }}"
    repo: "{{ repo.repo }}"
    update: false
  loop: "{{ repos }}"
  loop_control:
    loop_var: repo
