---

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present

- name: Add user to docker group
  user:
    append: true
    groups: docker
    name: "{{ ansible_env.SUDO_USER }}"
