---

- name: Get Latest URL
  shell: "wget \"https://data.services.jetbrains.com/products/releases?code=TBA&latest=true&type=release\" -O -| grep -o \"https://download.jetbrains.com/toolbox/jetbrains-toolbox-[0-9.]*.tar.gz\" | head -n 1"
  register: toolboxUrl

- name: Create destination directory
  file:
    path: /opt/jetbrains-toolbox
    state: directory

- name: Unpack JetBrains Toolbox
  unarchive:
    remote_src: true
    src: "{{ toolboxUrl.stdout }}"
    dest: /opt/jetbrains-toolbox
    creates: /opt/jetbrains-toolbox/jetbrains-toolbox
    extra_opts:
      - --strip-components=1

- name: Link to Toolbox
  file:
    src: /opt/jetbrains-toolbox/jetbrains-toolbox
    dest: /usr/bin/jetbrains-toolbox
    state: link

- name: Ensure IntelliJ projects get enough inotify watches
  sysctl:
    name: fs.inotify.max_user_watches
    value: 524288
    state: present
    sysctl_file: /etc/sysctl.d/intellij_inotify.conf
