---

- name: Install Microsoft GPG Key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg

- name: Install VSCode source
  copy:
    content: "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main"
    dest: /etc/apt/sources.list.d/vscode.list

- name: Install VSCode
  apt:
    name: code
    state: present
